import React,{useEffect,useState} from 'react';
import {Archive,ArrowLeft,CheckCircle,Pencil,Plus,RefreshCw,SlidersHorizontal} from 'lucide-react';

const API=import.meta.env.VITE_API_URL||'http://localhost:4000/api';
const request=async(path,options={})=>{const response=await fetch(`${API}${path}`,{headers:{'Content-Type':'application/json',...options.headers},...options});const data=await response.json().catch(()=>({}));if(!response.ok){const error=new Error(data.message||'Request failed');error.status=response.status;throw error}return data};

const groupTypes=[
  {value:'SAUCE',label:'Sauce'},
  {value:'EXTRA',label:'Extra'},
  {value:'ADD_ON',label:'Add-on'}
];

export default function Customizations({onBack}) {
  const [groups,setGroups]=useState([]),[status,setStatus]=useState('loading'),[showForm,setShowForm]=useState(false),[name,setName]=useState(''),[code,setCode]=useState(''),[groupType,setGroupType]=useState('SAUCE'),[formError,setFormError]=useState(''),[submitting,setSubmitting]=useState(false),[selectedGroup,setSelectedGroup]=useState(null),[editingGroup,setEditingGroup]=useState(null),[editName,setEditName]=useState(''),[editCode,setEditCode]=useState(''),[editError,setEditError]=useState(''),[editSubmitting,setEditSubmitting]=useState(false),[statusGroup,setStatusGroup]=useState(null),[statusError,setStatusError]=useState(''),[statusSubmitting,setStatusSubmitting]=useState(false);
  const loadGroups=async()=>{setStatus('loading');try{const data=await request('/admin/menu/customization-groups');setGroups(Array.isArray(data.groups)?data.groups:[]);setStatus('ready')}catch{setStatus('error')}};
  useEffect(()=>{loadGroups()},[]);
  const openForm=()=>{setEditingGroup(null);setEditError('');setStatusGroup(null);setStatusError('');setShowForm(true);setFormError('')};
  const closeForm=()=>{setShowForm(false);setName('');setCode('');setGroupType('SAUCE');setFormError('')};
  const openEdit=group=>{setShowForm(false);setFormError('');setStatusGroup(null);setStatusError('');setEditingGroup(group);setEditName(group.name);setEditCode(group.code);setEditError('')};
  const closeEdit=()=>{setEditingGroup(null);setEditName('');setEditCode('');setEditError('')};
  const openStatus=group=>{setShowForm(false);setFormError('');setEditingGroup(null);setEditError('');setStatusGroup(group);setStatusError('')};
  const closeStatus=()=>{setStatusGroup(null);setStatusError('')};
  const createGroup=async event=>{event.preventDefault();const trimmedName=name.trim();const trimmedCode=code.trim();if(!trimmedName){setFormError('Please enter a group name.');return}if(!trimmedCode){setFormError('Please enter a group code.');return}setSubmitting(true);setFormError('');try{await request('/admin/menu/customization-groups',{method:'POST',body:JSON.stringify({name:trimmedName,code:trimmedCode,group_type:groupType})});closeForm();await loadGroups()}catch(error){setFormError(error.status===400||error.status===409?error.message:'Unable to create customization group. Please try again.')}finally{setSubmitting(false)}};
  const updateGroup=async event=>{event.preventDefault();const trimmedName=editName.trim();const trimmedCode=editCode.trim();if(!trimmedName){setEditError('Please enter a group name.');return}if(!trimmedCode){setEditError('Please enter a group code.');return}setEditSubmitting(true);setEditError('');try{await request(`/admin/menu/customization-groups/${editingGroup.id}`,{method:'PATCH',body:JSON.stringify({name:trimmedName,code:trimmedCode})});closeEdit();await loadGroups()}catch(error){setEditError(error.status===400||error.status===409?error.message:error.status===404?'This customization group no longer exists. Please refresh the list.':'Unable to update customization group. Please try again.')}finally{setEditSubmitting(false)}};
  const updateStatus=async event=>{event.preventDefault();const nextStatus=!statusGroup.is_active;setStatusSubmitting(true);setStatusError('');try{await request(`/admin/menu/customization-groups/${statusGroup.id}/status`,{method:'PATCH',body:JSON.stringify({is_active:nextStatus})});closeStatus();await loadGroups()}catch(error){setStatusError(error.status===400?error.message:error.status===404?'This customization group no longer exists. Please refresh the list.':'Unable to update customization group status. Please try again.')}finally{setStatusSubmitting(false)}};
  if(selectedGroup)return <CustomizationOptions group={selectedGroup} onBack={()=>setSelectedGroup(null)}/>;
  return <section className="admin-customizations" aria-labelledby="customizations-title">
    <button className="admin-back-button" type="button" onClick={onBack}><ArrowLeft/> Back to Head Office</button>
    <header className="admin-customizations-header"><div className="admin-state-icon"><SlidersHorizontal/></div><div className="admin-customizations-title"><span className="admin-panel-eyebrow">HEAD OFFICE / MASTER MENU</span><h1 id="customizations-title">Customizations</h1><p>Manage master customization groups owned by Head Office.</p></div><button className="admin-primary-action" type="button" onClick={openForm}><Plus/> Add Group</button></header>
    <div className="admin-ownership-note"><SlidersHorizontal/><p>Customization groups are centrally managed by Head Office and apply to the Shawarmaholics master menu.</p></div>
    <div className="admin-section-heading admin-customization-section-heading"><span className="admin-panel-eyebrow">MASTER CONFIGURATION</span><h2>Customization Groups</h2><p>Set up the global groups that will later contain sauces, extras, and add-ons.</p></div>
    {showForm&&<form className="admin-customization-group-form" onSubmit={createGroup} noValidate><div><span className="admin-panel-eyebrow">NEW CUSTOMIZATION GROUP</span><h2>Add Group</h2><p>Create a master customization group for the centralized Shawarmaholics menu.</p></div><div className="admin-customization-form-grid"><label htmlFor="customization-group-name">Group Name *<input id="customization-group-name" value={name} onChange={event=>{setName(event.target.value);if(formError)setFormError('')}} placeholder="e.g. Sauces" autoComplete="off" autoFocus aria-invalid={Boolean(formError)} /></label><label htmlFor="customization-group-code">Group Code *<input id="customization-group-code" value={code} onChange={event=>{setCode(event.target.value);if(formError)setFormError('')}} placeholder="e.g. SAUCES" autoComplete="off" aria-invalid={Boolean(formError)} /></label><label htmlFor="customization-group-type">Group Type *<select id="customization-group-type" value={groupType} onChange={event=>setGroupType(event.target.value)}>{groupTypes.map(type=><option key={type.value} value={type.value}>{type.label}</option>)}</select></label></div>{formError&&<p className="admin-form-error" role="alert">{formError}</p>}<div className="admin-category-form-actions"><button className="admin-secondary-action" type="button" onClick={closeForm} disabled={submitting}>Cancel</button><button className="admin-primary-action" type="submit" disabled={submitting}>{submitting?'Creating...':'Create Group'}</button></div></form>}
    {editingGroup&&<form className="admin-customization-group-form admin-customization-group-edit-form" onSubmit={updateGroup} noValidate><div><span className="admin-panel-eyebrow">EDIT CUSTOMIZATION GROUP</span><h2>Edit Group</h2><p>Update the name and code of this centrally managed customization group. Type and position stay unchanged.</p></div><div className="admin-customization-form-grid admin-customization-option-form-grid"><label htmlFor="edit-customization-group-name">Group Name *<input id="edit-customization-group-name" value={editName} onChange={event=>{setEditName(event.target.value);if(editError)setEditError('')}} autoComplete="off" autoFocus aria-invalid={Boolean(editError)}/></label><label htmlFor="edit-customization-group-code">Group Code *<input id="edit-customization-group-code" value={editCode} onChange={event=>{setEditCode(event.target.value);if(editError)setEditError('')}} autoComplete="off" aria-invalid={Boolean(editError)}/></label></div>{editError&&<p className="admin-form-error" role="alert">{editError}</p>}<div className="admin-category-form-actions"><button className="admin-secondary-action" type="button" onClick={closeEdit} disabled={editSubmitting}>Cancel</button><button className="admin-primary-action" type="submit" disabled={editSubmitting}>{editSubmitting?'Saving...':'Save Changes'}</button></div></form>}
    {statusGroup&&<form className="admin-customization-group-form admin-category-status-form" onSubmit={updateStatus} noValidate role="dialog" aria-modal="true" aria-labelledby="customization-group-status-title"><div><span className="admin-panel-eyebrow">{statusGroup.is_active?'ARCHIVE GROUP':'ACTIVATE GROUP'}</span><h2 id="customization-group-status-title">{statusGroup.is_active?'Archive Group':'Activate Group'}</h2><p>{statusGroup.is_active?`Are you sure you want to archive '${statusGroup.name}'? Archiving keeps the group, its options, and existing menu-item assignments, but marks the group inactive.`:`Do you want to activate '${statusGroup.name}' again?`}</p></div>{statusError&&<p className="admin-form-error" role="alert">{statusError}</p>}<div className="admin-category-form-actions"><button className="admin-secondary-action" type="button" onClick={closeStatus} disabled={statusSubmitting}>Cancel</button><button className="admin-primary-action" type="submit" disabled={statusSubmitting}>{statusSubmitting?'Saving...':statusGroup.is_active?'Archive Group':'Activate Group'}</button></div></form>}
    {status==='loading'&&<div className="admin-branch-feedback" role="status">Loading customization groups...</div>}
    {status==='error'&&<div className="admin-branch-feedback admin-branch-feedback-error" role="alert"><p>Unable to load customization groups.</p><button className="admin-retry-button" type="button" onClick={loadGroups}><RefreshCw/> Retry</button></div>}
    {status==='ready'&&!groups.length&&<div className="admin-branch-feedback" role="status"><strong>No customization groups yet</strong><p>Create your first master customization group to begin configuring sauces, extras, and add-ons.</p></div>}
    {status==='ready'&&groups.length>0&&<div className="admin-customization-table-wrap"><table className="admin-customization-table"><caption className="sr-only">Head Office customization groups</caption><thead><tr><th scope="col">Group Name</th><th scope="col">Code</th><th scope="col">Type</th><th scope="col">Position</th><th scope="col">Status</th><th scope="col">Actions</th></tr></thead><tbody>{groups.map(group=><tr key={group.id}><td data-label="Group Name"><button className="admin-customization-group-link" type="button" onClick={()=>setSelectedGroup(group)}>{group.name}</button></td><td data-label="Code"><span className="admin-customization-code">{group.code}</span></td><td data-label="Type"><span className="admin-customization-type">{groupTypes.find(type=>type.value===group.group_type)?.label||group.group_type}</span></td><td data-label="Position"><span className="admin-category-order">#{group.position}</span></td><td data-label="Status"><span className={`admin-category-status ${group.is_active?'active':'archived'}`}><i/>{group.is_active?'Active':'Archived'}</span></td><td data-label="Actions"><div className="admin-category-actions"><button className="admin-category-edit-action" type="button" onClick={()=>setSelectedGroup(group)}>Manage Options</button><button className="admin-category-edit-action" type="button" onClick={()=>openEdit(group)} aria-label={`Edit ${group.name}`}><Pencil/> Edit</button><button className="admin-category-status-action" type="button" onClick={()=>openStatus(group)} aria-label={`${group.is_active?'Archive':'Activate'} ${group.name}`}>{group.is_active?<Archive/>:<CheckCircle/>}{group.is_active?'Archive':'Activate'}</button></div></td></tr>)}</tbody></table></div>}
  </section>;
}

function CustomizationOptions({group,onBack}) {
  const [options,setOptions]=useState([]),[status,setStatus]=useState('loading'),[showForm,setShowForm]=useState(false),[name,setName]=useState(''),[price,setPrice]=useState(''),[formError,setFormError]=useState(''),[submitting,setSubmitting]=useState(false),[editingOption,setEditingOption]=useState(null),[editName,setEditName]=useState(''),[editPrice,setEditPrice]=useState(''),[editError,setEditError]=useState(''),[editSubmitting,setEditSubmitting]=useState(false),[statusOption,setStatusOption]=useState(null),[statusError,setStatusError]=useState(''),[statusSubmitting,setStatusSubmitting]=useState(false);
  const typeLabel=groupTypes.find(type=>type.value===group.group_type)?.label||group.group_type;
  const loadOptions=async()=>{setStatus('loading');try{const data=await request(`/admin/menu/customization-groups/${group.id}/options`);setOptions(Array.isArray(data.options)?data.options:[]);setStatus('ready')}catch{setStatus('error')}};
  useEffect(()=>{loadOptions()},[group.id]);
  const openForm=()=>{setEditingOption(null);setEditError('');setStatusOption(null);setStatusError('');setShowForm(true);setFormError('')};
  const closeForm=()=>{setShowForm(false);setName('');setPrice('');setFormError('')};
  const openEdit=option=>{setShowForm(false);setFormError('');setStatusOption(null);setStatusError('');setEditingOption(option);setEditName(option.name);setEditPrice(String(option.price));setEditError('')};
  const closeEdit=()=>{setEditingOption(null);setEditName('');setEditPrice('');setEditError('')};
  const openStatus=option=>{setShowForm(false);setFormError('');setEditingOption(null);setEditError('');setStatusOption(option);setStatusError('')};
  const closeStatus=()=>{setStatusOption(null);setStatusError('')};
  const createOption=async event=>{event.preventDefault();const trimmedName=name.trim();const numericPrice=Number(price);if(!trimmedName){setFormError('Please enter an option name.');return}if(price.trim()===''||!Number.isFinite(numericPrice)||numericPrice<0){setFormError('Enter a valid non-negative price.');return}setSubmitting(true);setFormError('');try{await request(`/admin/menu/customization-groups/${group.id}/options`,{method:'POST',body:JSON.stringify({name:trimmedName,price:numericPrice})});closeForm();await loadOptions()}catch(error){setFormError(error.status===400||error.status===404||error.status===409?error.message:'Unable to create customization option. Please try again.')}finally{setSubmitting(false)}};
  const updateOption=async event=>{event.preventDefault();const trimmedName=editName.trim(),numericPrice=Number(editPrice);if(!trimmedName){setEditError('Please enter an option name.');return}if(editPrice.trim()===''||!Number.isFinite(numericPrice)||numericPrice<0){setEditError('Enter a valid non-negative price.');return}setEditSubmitting(true);setEditError('');try{await request(`/admin/menu/customization-groups/${group.id}/options/${editingOption.id}`,{method:'PATCH',body:JSON.stringify({name:trimmedName,price:numericPrice})});closeEdit();await loadOptions()}catch(error){setEditError(error.status===400||error.status===409?error.message:error.status===404?'This customization option no longer exists. Please refresh the list.':'Unable to update customization option. Please try again.')}finally{setEditSubmitting(false)}};
  const updateStatus=async event=>{event.preventDefault();const nextStatus=!statusOption.is_active;setStatusSubmitting(true);setStatusError('');try{await request(`/admin/menu/customization-groups/${group.id}/options/${statusOption.id}/status`,{method:'PATCH',body:JSON.stringify({is_active:nextStatus})});closeStatus();await loadOptions()}catch(error){setStatusError(error.status===400?error.message:error.status===404?'This customization option no longer exists. Please refresh the list.':'Unable to update customization option status. Please try again.')}finally{setStatusSubmitting(false)}};
  const money=value=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(Number(value));
  return <section className="admin-customizations admin-customization-options" aria-labelledby="customization-options-title">
    <button className="admin-back-button" type="button" onClick={onBack}><ArrowLeft/> Back to Groups</button>
    <header className="admin-customizations-header"><div className="admin-state-icon"><SlidersHorizontal/></div><div className="admin-customizations-title"><span className="admin-panel-eyebrow">CUSTOMIZATION GROUP</span><h1 id="customization-options-title">{group.name}</h1><p><strong>{group.code}</strong> · {typeLabel} · Position #{group.position}</p></div><button className="admin-primary-action" type="button" onClick={openForm} disabled={!group.is_active}><Plus/> Add Option</button></header>
    {!group.is_active&&<div className="admin-ownership-note"><SlidersHorizontal/><p>This group is archived. Existing options remain visible, but new options cannot be created.</p></div>}
    <div className="admin-section-heading admin-customization-section-heading"><span className="admin-panel-eyebrow">GROUP OPTIONS</span><h2>Customization Options</h2><p>Manage the options available within this master customization group.</p></div>
    {showForm&&<form className="admin-customization-group-form" onSubmit={createOption} noValidate><div><span className="admin-panel-eyebrow">NEW CUSTOMIZATION OPTION</span><h2>Add Option</h2><p>Create an option for the {group.name} group.</p></div><div className="admin-customization-form-grid admin-customization-option-form-grid"><label htmlFor="customization-option-name">Option Name *<input id="customization-option-name" value={name} onChange={event=>{setName(event.target.value);if(formError)setFormError('')}} placeholder="e.g. Garlic Sauce" autoComplete="off" autoFocus aria-invalid={Boolean(formError)}/></label><label htmlFor="customization-option-price">Price *<input id="customization-option-price" value={price} onChange={event=>{setPrice(event.target.value);if(formError)setFormError('')}} placeholder="0" type="number" min="0" step="0.01" aria-invalid={Boolean(formError)}/></label></div>{formError&&<p className="admin-form-error" role="alert">{formError}</p>}<div className="admin-category-form-actions"><button className="admin-secondary-action" type="button" onClick={closeForm} disabled={submitting}>Cancel</button><button className="admin-primary-action" type="submit" disabled={submitting}>{submitting?'Creating...':'Create Option'}</button></div></form>}
    {editingOption&&<form className="admin-customization-group-form admin-customization-group-edit-form" onSubmit={updateOption} noValidate><div><span className="admin-panel-eyebrow">EDIT CUSTOMIZATION OPTION</span><h2>Edit Option</h2><p>Update this master option’s name and price. Its group, position, and lifecycle stay unchanged.</p></div><div className="admin-customization-form-grid admin-customization-option-form-grid"><label htmlFor="edit-customization-option-name">Option Name *<input id="edit-customization-option-name" value={editName} onChange={event=>{setEditName(event.target.value);if(editError)setEditError('')}} autoComplete="off" autoFocus aria-invalid={Boolean(editError)}/></label><label htmlFor="edit-customization-option-price">Price *<input id="edit-customization-option-price" value={editPrice} onChange={event=>{setEditPrice(event.target.value);if(editError)setEditError('')}} type="number" min="0" step="0.01" aria-invalid={Boolean(editError)}/></label></div>{editError&&<p className="admin-form-error" role="alert">{editError}</p>}<div className="admin-category-form-actions"><button className="admin-secondary-action" type="button" onClick={closeEdit} disabled={editSubmitting}>Cancel</button><button className="admin-primary-action" type="submit" disabled={editSubmitting}>{editSubmitting?'Saving...':'Save Changes'}</button></div></form>}
    {statusOption&&<form className="admin-customization-group-form admin-category-status-form" onSubmit={updateStatus} noValidate role="dialog" aria-modal="true" aria-labelledby="customization-option-status-title"><div><span className="admin-panel-eyebrow">{statusOption.is_active?'ARCHIVE OPTION':'ACTIVATE OPTION'}</span><h2 id="customization-option-status-title">{statusOption.is_active?'Archive Option':'Activate Option'}</h2><p>{statusOption.is_active?`Are you sure you want to archive '${statusOption.name}'? Archiving keeps the option and its existing relationships, but marks it inactive.`:`Do you want to activate '${statusOption.name}' again?`}</p></div>{statusError&&<p className="admin-form-error" role="alert">{statusError}</p>}<div className="admin-category-form-actions"><button className="admin-secondary-action" type="button" onClick={closeStatus} disabled={statusSubmitting}>Cancel</button><button className="admin-primary-action" type="submit" disabled={statusSubmitting}>{statusSubmitting?'Saving...':statusOption.is_active?'Archive Option':'Activate Option'}</button></div></form>}
    {status==='loading'&&<div className="admin-branch-feedback" role="status">Loading customization options...</div>}
    {status==='error'&&<div className="admin-branch-feedback admin-branch-feedback-error" role="alert"><p>Unable to load customization options.</p><button className="admin-retry-button" type="button" onClick={loadOptions}><RefreshCw/> Retry</button></div>}
    {status==='ready'&&!options.length&&<div className="admin-branch-feedback" role="status"><strong>No customization options yet</strong><p>Create the first option for this group.</p></div>}
    {status==='ready'&&options.length>0&&<div className="admin-customization-table-wrap"><table className="admin-customization-table"><caption className="sr-only">Customization options for {group.name}</caption><thead><tr><th scope="col">Option Name</th><th scope="col">Price</th><th scope="col">Position</th><th scope="col">Status</th><th scope="col">Actions</th></tr></thead><tbody>{options.map(option=><tr key={option.id}><td data-label="Option Name"><strong>{option.name}</strong></td><td data-label="Price"><span className="admin-menu-price">{money(option.price)}</span></td><td data-label="Position"><span className="admin-category-order">#{option.position}</span></td><td data-label="Status"><span className={`admin-category-status ${option.is_active?'active':'archived'}`}><i/>{option.is_active?'Active':'Archived'}</span></td><td data-label="Actions"><div className="admin-category-actions"><button className="admin-category-edit-action" type="button" onClick={()=>openEdit(option)} aria-label={`Edit ${option.name}`}><Pencil/> Edit</button><button className="admin-category-status-action" type="button" onClick={()=>openStatus(option)} aria-label={`${option.is_active?'Archive':'Activate'} ${option.name}`}>{option.is_active?<Archive/>:<CheckCircle/>}{option.is_active?'Archive':'Activate'}</button></div></td></tr>)}</tbody></table></div>}
  </section>;
}
