import React,{useEffect,useState} from 'react';
import {ArrowLeft,Plus,RefreshCw,SlidersHorizontal} from 'lucide-react';

const API=import.meta.env.VITE_API_URL||'http://localhost:4000/api';
const request=async(path,options={})=>{const response=await fetch(`${API}${path}`,{headers:{'Content-Type':'application/json',...options.headers},...options});const data=await response.json().catch(()=>({}));if(!response.ok){const error=new Error(data.message||'Request failed');error.status=response.status;throw error}return data};

const groupTypes=[
  {value:'SAUCE',label:'Sauce'},
  {value:'EXTRA',label:'Extra'},
  {value:'ADD_ON',label:'Add-on'}
];

export default function Customizations({onBack}) {
  const [groups,setGroups]=useState([]),[status,setStatus]=useState('loading'),[showForm,setShowForm]=useState(false),[name,setName]=useState(''),[code,setCode]=useState(''),[groupType,setGroupType]=useState('SAUCE'),[formError,setFormError]=useState(''),[submitting,setSubmitting]=useState(false),[selectedGroup,setSelectedGroup]=useState(null);
  const loadGroups=async()=>{setStatus('loading');try{const data=await request('/admin/menu/customization-groups');setGroups(Array.isArray(data.groups)?data.groups:[]);setStatus('ready')}catch{setStatus('error')}};
  useEffect(()=>{loadGroups()},[]);
  const openForm=()=>{setShowForm(true);setFormError('')};
  const closeForm=()=>{setShowForm(false);setName('');setCode('');setGroupType('SAUCE');setFormError('')};
  const createGroup=async event=>{event.preventDefault();const trimmedName=name.trim();const trimmedCode=code.trim();if(!trimmedName){setFormError('Please enter a group name.');return}if(!trimmedCode){setFormError('Please enter a group code.');return}setSubmitting(true);setFormError('');try{await request('/admin/menu/customization-groups',{method:'POST',body:JSON.stringify({name:trimmedName,code:trimmedCode,group_type:groupType})});closeForm();await loadGroups()}catch(error){setFormError(error.status===400||error.status===409?error.message:'Unable to create customization group. Please try again.')}finally{setSubmitting(false)}};
  if(selectedGroup)return <CustomizationOptions group={selectedGroup} onBack={()=>setSelectedGroup(null)}/>;
  return <section className="admin-customizations" aria-labelledby="customizations-title">
    <button className="admin-back-button" type="button" onClick={onBack}><ArrowLeft/> Back to Head Office</button>
    <header className="admin-customizations-header"><div className="admin-state-icon"><SlidersHorizontal/></div><div className="admin-customizations-title"><span className="admin-panel-eyebrow">HEAD OFFICE / MASTER MENU</span><h1 id="customizations-title">Customizations</h1><p>Manage master customization groups owned by Head Office.</p></div><button className="admin-primary-action" type="button" onClick={openForm}><Plus/> Add Group</button></header>
    <div className="admin-ownership-note"><SlidersHorizontal/><p>Customization groups are centrally managed by Head Office and apply to the Shawarmaholics master menu.</p></div>
    <div className="admin-section-heading admin-customization-section-heading"><span className="admin-panel-eyebrow">MASTER CONFIGURATION</span><h2>Customization Groups</h2><p>Set up the global groups that will later contain sauces, extras, and add-ons.</p></div>
    {showForm&&<form className="admin-customization-group-form" onSubmit={createGroup} noValidate><div><span className="admin-panel-eyebrow">NEW CUSTOMIZATION GROUP</span><h2>Add Group</h2><p>Create a master customization group for the centralized Shawarmaholics menu.</p></div><div className="admin-customization-form-grid"><label htmlFor="customization-group-name">Group Name *<input id="customization-group-name" value={name} onChange={event=>{setName(event.target.value);if(formError)setFormError('')}} placeholder="e.g. Sauces" autoComplete="off" autoFocus aria-invalid={Boolean(formError)} /></label><label htmlFor="customization-group-code">Group Code *<input id="customization-group-code" value={code} onChange={event=>{setCode(event.target.value);if(formError)setFormError('')}} placeholder="e.g. SAUCES" autoComplete="off" aria-invalid={Boolean(formError)} /></label><label htmlFor="customization-group-type">Group Type *<select id="customization-group-type" value={groupType} onChange={event=>setGroupType(event.target.value)}>{groupTypes.map(type=><option key={type.value} value={type.value}>{type.label}</option>)}</select></label></div>{formError&&<p className="admin-form-error" role="alert">{formError}</p>}<div className="admin-category-form-actions"><button className="admin-secondary-action" type="button" onClick={closeForm} disabled={submitting}>Cancel</button><button className="admin-primary-action" type="submit" disabled={submitting}>{submitting?'Creating...':'Create Group'}</button></div></form>}
    {status==='loading'&&<div className="admin-branch-feedback" role="status">Loading customization groups...</div>}
    {status==='error'&&<div className="admin-branch-feedback admin-branch-feedback-error" role="alert"><p>Unable to load customization groups.</p><button className="admin-retry-button" type="button" onClick={loadGroups}><RefreshCw/> Retry</button></div>}
    {status==='ready'&&!groups.length&&<div className="admin-branch-feedback" role="status"><strong>No customization groups yet</strong><p>Create your first master customization group to begin configuring sauces, extras, and add-ons.</p></div>}
    {status==='ready'&&groups.length>0&&<div className="admin-customization-table-wrap"><table className="admin-customization-table"><caption className="sr-only">Head Office customization groups</caption><thead><tr><th scope="col">Group Name</th><th scope="col">Code</th><th scope="col">Type</th><th scope="col">Position</th><th scope="col">Status</th><th scope="col">Actions</th></tr></thead><tbody>{groups.map(group=><tr key={group.id}><td data-label="Group Name"><button className="admin-customization-group-link" type="button" onClick={()=>setSelectedGroup(group)}>{group.name}</button></td><td data-label="Code"><span className="admin-customization-code">{group.code}</span></td><td data-label="Type"><span className="admin-customization-type">{groupTypes.find(type=>type.value===group.group_type)?.label||group.group_type}</span></td><td data-label="Position"><span className="admin-category-order">#{group.position}</span></td><td data-label="Status"><span className={`admin-category-status ${group.is_active?'active':'archived'}`}><i/>{group.is_active?'Active':'Archived'}</span></td><td data-label="Actions"><button className="admin-category-edit-action" type="button" onClick={()=>setSelectedGroup(group)}>Manage Options</button></td></tr>)}</tbody></table></div>}
  </section>;
}

function CustomizationOptions({group,onBack}) {
  const [options,setOptions]=useState([]),[status,setStatus]=useState('loading'),[showForm,setShowForm]=useState(false),[name,setName]=useState(''),[price,setPrice]=useState(''),[formError,setFormError]=useState(''),[submitting,setSubmitting]=useState(false);
  const typeLabel=groupTypes.find(type=>type.value===group.group_type)?.label||group.group_type;
  const loadOptions=async()=>{setStatus('loading');try{const data=await request(`/admin/menu/customization-groups/${group.id}/options`);setOptions(Array.isArray(data.options)?data.options:[]);setStatus('ready')}catch{setStatus('error')}};
  useEffect(()=>{loadOptions()},[group.id]);
  const closeForm=()=>{setShowForm(false);setName('');setPrice('');setFormError('')};
  const createOption=async event=>{event.preventDefault();const trimmedName=name.trim();const numericPrice=Number(price);if(!trimmedName){setFormError('Please enter an option name.');return}if(price.trim()===''||!Number.isFinite(numericPrice)||numericPrice<0){setFormError('Enter a valid non-negative price.');return}setSubmitting(true);setFormError('');try{await request(`/admin/menu/customization-groups/${group.id}/options`,{method:'POST',body:JSON.stringify({name:trimmedName,price:numericPrice})});closeForm();await loadOptions()}catch(error){setFormError(error.status===400||error.status===404||error.status===409?error.message:'Unable to create customization option. Please try again.')}finally{setSubmitting(false)}};
  const money=value=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(Number(value));
  return <section className="admin-customizations admin-customization-options" aria-labelledby="customization-options-title">
    <button className="admin-back-button" type="button" onClick={onBack}><ArrowLeft/> Back to Groups</button>
    <header className="admin-customizations-header"><div className="admin-state-icon"><SlidersHorizontal/></div><div className="admin-customizations-title"><span className="admin-panel-eyebrow">CUSTOMIZATION GROUP</span><h1 id="customization-options-title">{group.name}</h1><p><strong>{group.code}</strong> · {typeLabel} · Position #{group.position}</p></div><button className="admin-primary-action" type="button" onClick={()=>{setShowForm(true);setFormError('')}} disabled={!group.is_active}><Plus/> Add Option</button></header>
    {!group.is_active&&<div className="admin-ownership-note"><SlidersHorizontal/><p>This group is archived. Existing options remain visible, but new options cannot be created.</p></div>}
    <div className="admin-section-heading admin-customization-section-heading"><span className="admin-panel-eyebrow">GROUP OPTIONS</span><h2>Customization Options</h2><p>Manage the options available within this master customization group.</p></div>
    {showForm&&<form className="admin-customization-group-form" onSubmit={createOption} noValidate><div><span className="admin-panel-eyebrow">NEW CUSTOMIZATION OPTION</span><h2>Add Option</h2><p>Create an option for the {group.name} group.</p></div><div className="admin-customization-form-grid admin-customization-option-form-grid"><label htmlFor="customization-option-name">Option Name *<input id="customization-option-name" value={name} onChange={event=>{setName(event.target.value);if(formError)setFormError('')}} placeholder="e.g. Garlic Sauce" autoComplete="off" autoFocus aria-invalid={Boolean(formError)}/></label><label htmlFor="customization-option-price">Price *<input id="customization-option-price" value={price} onChange={event=>{setPrice(event.target.value);if(formError)setFormError('')}} placeholder="0" type="number" min="0" step="0.01" aria-invalid={Boolean(formError)}/></label></div>{formError&&<p className="admin-form-error" role="alert">{formError}</p>}<div className="admin-category-form-actions"><button className="admin-secondary-action" type="button" onClick={closeForm} disabled={submitting}>Cancel</button><button className="admin-primary-action" type="submit" disabled={submitting}>{submitting?'Creating...':'Create Option'}</button></div></form>}
    {status==='loading'&&<div className="admin-branch-feedback" role="status">Loading customization options...</div>}
    {status==='error'&&<div className="admin-branch-feedback admin-branch-feedback-error" role="alert"><p>Unable to load customization options.</p><button className="admin-retry-button" type="button" onClick={loadOptions}><RefreshCw/> Retry</button></div>}
    {status==='ready'&&!options.length&&<div className="admin-branch-feedback" role="status"><strong>No customization options yet</strong><p>Create the first option for this group.</p></div>}
    {status==='ready'&&options.length>0&&<div className="admin-customization-table-wrap"><table className="admin-customization-table"><caption className="sr-only">Customization options for {group.name}</caption><thead><tr><th scope="col">Option Name</th><th scope="col">Price</th><th scope="col">Position</th><th scope="col">Status</th></tr></thead><tbody>{options.map(option=><tr key={option.id}><td data-label="Option Name"><strong>{option.name}</strong></td><td data-label="Price"><span className="admin-menu-price">{money(option.price)}</span></td><td data-label="Position"><span className="admin-category-order">#{option.position}</span></td><td data-label="Status"><span className={`admin-category-status ${option.is_active?'active':'archived'}`}><i/>{option.is_active?'Active':'Archived'}</span></td></tr>)}</tbody></table></div>}
  </section>;
}
