import React, { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, ClipboardList, PackagePlus, RefreshCw, Search } from 'lucide-react';
import './inventory.css';

const API=import.meta.env.VITE_API_URL||'http://localhost:4000/api';
async function request(path,token,options={}){const response=await fetch(API+path,{...options,headers:{'Content-Type':'application/json',...(token?{Authorization:\`Bearer \${token}\`}:{}),...(options.headers||{})}});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||'Request failed');return data;}
const movementLabels={RECEIPT:'Receive stock',ADJUSTMENT_IN:'Adjustment in',ADJUSTMENT_OUT:'Adjustment out',WASTE:'Waste',RETURN:'Return'};
const displayQty=v=>Number(v).toFixed(3).replace(/\\.000$/,'');

export default function InventoryManagement({adminToken,onBack}){
 const [branches,setBranches]=useState([]),[items,setItems]=useState([]),[stock,setStock]=useState([]),[movements,setMovements]=useState([]);
 const [branchId,setBranchId]=useState(''),[itemId,setItemId]=useState(''),[search,setSearch]=useState(''),[lowStock,setLowStock]=useState(false);
 const [showItemForm,setShowItemForm]=useState(false),[showMovementForm,setShowMovementForm]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState('');
 const [itemForm,setItemForm]=useState({name:'',sku:'',unit:'kg',lowStockThreshold:'0'});
 const [movementForm,setMovementForm]=useState({branchId:'',inventoryItemId:'',movementType:'RECEIPT',quantity:'',unitCost:'',reason:''});

 const load=async()=>{setLoading(true);setError('');try{const q=new URLSearchParams();if(branchId)q.set('branchId',branchId);if(search.trim())q.set('search',search.trim());if(lowStock)q.set('lowStock','true');const b=await request('/branches',adminToken),i=await request('/admin/inventory/items',adminToken),s=await request('/admin/inventory?'+q.toString(),adminToken),m=await request('/admin/inventory/movements?'+new URLSearchParams(branchId?{branchId,limit:'80'}:{limit:'80'}),adminToken);setBranches(b.branches||[]);setItems(i.items||[]);setStock(s.items||[]);setMovements(m.movements||[]);if(!movementForm.branchId&&b.branches?.[0])setMovementForm(v=>({...v,branchId:String(b.branches[0].id)}));if(!movementForm.inventoryItemId&&i.items?.[0])setMovementForm(v=>({...v,inventoryItemId:String(i.items[0].id)}));}catch(e){setError(e.message)}finally{setLoading(false)}};
 useEffect(()=>{load()},[branchId,lowStock]);
 const filteredStock=useMemo(()=>stock.filter(r=>!itemId||String(r.id)===String(itemId)),[stock,itemId]);
 const lowCount=stock.filter(r=>Number(r.quantity)<=Number(r.low_stock_threshold)).length;
 const createItem=async e=>{e.preventDefault();setError('');setMessage('');try{await request('/admin/inventory/items',adminToken,{method:'POST',body:JSON.stringify({name:itemForm.name,sku:itemForm.sku,unit:itemForm.unit,lowStockThreshold:Number(itemForm.lowStockThreshold)})});setItemForm({name:'',sku:'',unit:'kg',lowStockThreshold:'0'});setShowItemForm(false);setMessage('Inventory item created.');await load()}catch(e){setError(e.message)}};
 const postMovement=async e=>{e.preventDefault();setError('');setMessage('');try{await request('/admin/inventory/movements',adminToken,{method:'POST',body:JSON.stringify({...movementForm,branchId:Number(movementForm.branchId),inventoryItemId:Number(movementForm.inventoryItemId),quantity:Number(movementForm.quantity),unitCost:movementForm.unitCost===''?null:Number(movementForm.unitCost)})});setMovementForm(v=>({...v,quantity:'',unitCost:'',reason:''}));setShowMovementForm(false);setMessage('Stock movement posted.');await load()}catch(e){setError(e.message)}};
 return <section className="admin-inventory-page">
  <header className="admin-inventory-header"><button className="admin-back-button" type="button" onClick={onBack}><ArrowLeft/> Back to Head Office</button><div className="admin-inventory-heading"><span className="admin-panel-eyebrow">HEAD OFFICE • INVENTORY</span><h1>Inventory Management</h1><p>Track branch stock, receive goods, record adjustments and monitor low-stock items.</p></div><div className="admin-inventory-actions"><button className="admin-secondary-action" type="button" onClick={load}><RefreshCw/> Refresh</button><button className="admin-primary-action" type="button" onClick={()=>setShowMovementForm(v=>!v)}><PackagePlus/> Stock movement</button><button className="admin-primary-action" type="button" onClick={()=>setShowItemForm(v=>!v)}><ClipboardList/> New item</button></div></header>
  <div className="admin-inventory-stats"><article><span>Tracked items</span><strong>{items.length}</strong></article><article><span>Visible stock rows</span><strong>{filteredStock.length}</strong></article><article className={lowCount?'warning':''}><span>Low stock</span><strong>{lowCount}</strong></article><article><span>Recent movements</span><strong>{movements.length}</strong></article></div>
  {showItemForm&&<form className="admin-inventory-form" onSubmit={createItem}><div><span className="admin-panel-eyebrow">ITEM MASTER</span><h2>Add inventory item</h2></div><label>Name<input value={itemForm.name} onChange={e=>setItemForm(v=>({...v,name:e.target.value}))} placeholder="Chicken breast" required/></label><label>SKU<input value={itemForm.sku} onChange={e=>setItemForm(v=>({...v,sku:e.target.value}))} placeholder="Auto-generated if blank"/></label><label>Unit<select value={itemForm.unit} onChange={e=>setItemForm(v=>({...v,unit:e.target.value}))}><option>kg</option><option>g</option><option>ltr</option><option>ml</option><option>pcs</option><option>pack</option><option>box</option></select></label><label>Low-stock threshold<input type="number" min="0" step="0.001" value={itemForm.lowStockThreshold} onChange={e=>setItemForm(v=>({...v,lowStockThreshold:e.target.value}))}/></label><div className="admin-inventory-form-actions"><button className="admin-secondary-action" type="button" onClick={()=>setShowItemForm(false)}>Cancel</button><button className="admin-primary-action" type="submit">Create item</button></div></form>}
  {showMovementForm&&<form className="admin-inventory-form" onSubmit={postMovement}><div><span className="admin-panel-eyebrow">STOCK LEDGER</span><h2>Post stock movement</h2></div><label>Branch<select value={movementForm.branchId} onChange={e=>setMovementForm(v=>({...v,branchId:e.target.value}))} required><option value="">Select branch</option>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label>Inventory item<select value={movementForm.inventoryItemId} onChange={e=>setMovementForm(v=>({...v,inventoryItemId:e.target.value}))} required><option value="">Select item</option>{items.filter(i=>i.is_active).map(i=><option key={i.id} value={i.id}>{i.name} ({i.unit})</option>)}</select></label><label>Movement<select value={movementForm.movementType} onChange={e=>setMovementForm(v=>({...v,movementType:e.target.value}))}>{Object.entries(movementLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Quantity<input type="number" min="0.001" step="0.001" value={movementForm.quantity} onChange={e=>setMovementForm(v=>({...v,quantity:e.target.value}))} required/></label><label>Unit cost<input type="number" min="0" step="0.01" value={movementForm.unitCost} onChange={e=>setMovementForm(v=>({...v,unitCost:e.target.value}))} placeholder="Optional"/></label><label>Reason<input value={movementForm.reason} onChange={e=>setMovementForm(v=>({...v,reason:e.target.value}))} placeholder="Required for adjustments/waste"/></label><div className="admin-inventory-form-actions"><button className="admin-secondary-action" type="button" onClick={()=>setShowMovementForm(false)}>Cancel</button><button className="admin-primary-action" type="submit">Post movement</button></div></form>}
  {error&&<div className="admin-inventory-alert error">{error}</div>}{message&&<div className="admin-inventory-alert success">{message}</div>}
  <div className="admin-inventory-toolbar"><label><span>Branch</span><select value={branchId} onChange={e=>setBranchId(e.target.value)}><option value="">All branches</option>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label><span>Item</span><select value={itemId} onChange={e=>setItemId(e.target.value)}><option value="">All items</option>{items.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select></label><label className="admin-inventory-search"><span>Search</span><Search/><input value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load()} placeholder="Search item or SKU"/></label><label className="admin-inventory-checkbox"><input type="checkbox" checked={lowStock} onChange={e=>setLowStock(e.target.checked)}/><span>Low stock only</span></label></div>
  <div className="admin-inventory-table-wrap">{loading?<p className="admin-inventory-empty">Loading inventory…</p>:filteredStock.length?<table className="admin-inventory-table"><thead><tr><th>Item</th><th>SKU</th><th>Branch</th><th>On hand</th><th>Threshold</th><th>Status</th></tr></thead><tbody>{filteredStock.map(r=>{const low=Number(r.quantity)<=Number(r.low_stock_threshold);return <tr key={String(r.branch_id)+'-'+r.id}><td><strong>{r.name}</strong><small>{r.unit}</small></td><td>{r.sku}</td><td>{r.branch_name}</td><td><strong>{displayQty(r.quantity)}</strong> {r.unit}</td><td>{displayQty(r.low_stock_threshold)} {r.unit}</td><td><span className={'admin-inventory-status '+(low?'low':'ok')}>{low?'LOW':'OK'}</span></td></tr>})}</tbody></table>:<p className="admin-inventory-empty">No inventory rows match the current filters.</p>}</div>
  <section className="admin-inventory-history"><div className="admin-inventory-section-heading"><div><span className="admin-panel-eyebrow">AUDIT TRAIL</span><h2>Recent stock movements</h2></div></div><div className="admin-inventory-table-wrap">{movements.length?<table className="admin-inventory-table"><thead><tr><th>When</th><th>Item</th><th>Branch</th><th>Movement</th><th>Qty</th><th>Reason</th></tr></thead><tbody>{movements.map(m=><tr key={m.id}><td>{new Date(m.created_at).toLocaleString()}</td><td><strong>{m.item_name}</strong><small>{m.sku}</small></td><td>{m.branch_name}</td><td>{movementLabels[m.movement_type]||m.movement_type}</td><td>{displayQty(m.quantity)} {m.unit}</td><td>{m.reason||'—'}</td></tr>)}</tbody></table>:<p className="admin-inventory-empty">No stock movements yet.</p>}</div></section>
 </section>;
}
