import React, { useEffect, useState } from 'react';
import { ArrowLeft, FolderTree, Plus, RefreshCw, Pencil, Archive, CheckCircle } from 'lucide-react';

const API = import.meta.env.VITE_API_URL || 'http://localhost:4000/api';
const request = async (path, options = {}) => { const token = sessionStorage.getItem('shawarmaholics_admin_token') || ''; const response = await fetch(`${API}${path}`, { headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: 'Bearer ' + token } : {}), ...options.headers }, ...options }); const data = await response.json().catch(() => ({})); if (!response.ok) { const error = new Error(data.message || 'Request failed'); error.status = response.status; throw error } return data };

export default function MasterCategories({ onBack }) {
  const [categories, setCategories] = useState([]), [status, setStatus] = useState('loading'), [showForm, setShowForm] = useState(false), [name, setName] = useState(''), [formError, setFormError] = useState(''), [submitting, setSubmitting] = useState(false), [editingCategory, setEditingCategory] = useState(null), [editName, setEditName] = useState(''), [editError, setEditError] = useState(''), [editSubmitting, setEditSubmitting] = useState(false), [statusCategory, setStatusCategory] = useState(null), [statusError, setStatusError] = useState(''), [statusSubmitting, setStatusSubmitting] = useState(false);
  const loadCategories = () => { setStatus('loading'); request('/admin/menu/categories').then(data => { setCategories(Array.isArray(data.categories) ? data.categories : []); setStatus('ready') }).catch(() => setStatus('error')) };
  useEffect(() => { loadCategories() }, []);
  const openForm = () => { setEditingCategory(null); setEditError(''); setShowForm(true); setFormError('') };
  const closeForm = () => { setShowForm(false); setName(''); setFormError('') };
  const openEdit = category => { setShowForm(false); setFormError(''); setEditingCategory(category); setEditName(category.name); setEditError('') };
  const closeEdit = () => { setEditingCategory(null); setEditName(''); setEditError('') };
  const openStatus = category => { setShowForm(false); setEditingCategory(null); setStatusCategory(category); setStatusError('') };
  const closeStatus = () => { setStatusCategory(null); setStatusError('') };
  const createCategory = async event => { event.preventDefault(); const trimmed = name.trim(); if (!trimmed) { setFormError('Please enter a category name.'); return } setSubmitting(true); setFormError(''); try { await request('/admin/menu/categories', { method: 'POST', body: JSON.stringify({ name: trimmed }) }); closeForm(); await loadCategories() } catch (error) { setFormError(error.status === 400 ? error.message : error.status === 409 ? 'A category with this name already exists.' : 'Unable to create category. Please try again.') } finally { setSubmitting(false) } };
  const updateCategory = async event => { event.preventDefault(); const trimmed = editName.trim(); if (!trimmed) { setEditError('Please enter a category name.'); return } setEditSubmitting(true); setEditError(''); try { await request(`/admin/menu/categories/${editingCategory.id}`, { method: 'PATCH', body: JSON.stringify({ name: trimmed }) }); closeEdit(); await loadCategories() } catch (error) { setEditError(error.status === 400 ? error.message : error.status === 404 ? 'This category no longer exists. Please refresh the list.' : error.status === 409 ? 'A category with this name already exists.' : 'Unable to update category. Please try again.') } finally { setEditSubmitting(false) } };
  const updateStatus = async event => { event.preventDefault(); const nextStatus = !statusCategory.is_active; setStatusSubmitting(true); setStatusError(''); try { await request(`/admin/menu/categories/${statusCategory.id}/status`, { method: 'PATCH', body: JSON.stringify({ is_active: nextStatus }) }); closeStatus(); await loadCategories() } catch (error) { setStatusError(error.status === 400 ? error.message : error.status === 404 ? 'This category no longer exists. Please refresh the list.' : 'Unable to update category status. Please try again.') } finally { setStatusSubmitting(false) } };
  return <section className="admin-master-categories" aria-labelledby="master-categories-title">
    <button className="admin-back-button" type="button" onClick={onBack}><ArrowLeft /> Back to Head Office</button>
    <header className="admin-master-categories-header">
      <div className="admin-state-icon"><FolderTree /></div>
      <div className="admin-master-categories-title"><span className="admin-panel-eyebrow">HEAD OFFICE / MASTER MENU</span><h1 id="master-categories-title">Master Categories</h1><p>Manage the categories used across the Shawarmaholics master menu.</p></div>
      <button className="admin-primary-action" type="button" onClick={openForm}><Plus /> Add Category</button>
    </header>
    <div className="admin-ownership-note"><FolderTree /><p>Categories are centrally managed by Head Office and apply across all branches.</p></div>
    {showForm && <form className="admin-category-form" onSubmit={createCategory} noValidate><div><span className="admin-panel-eyebrow">NEW MASTER CATEGORY</span><h2>Add Master Category</h2><p>Create a new category for the centralized Shawarmaholics master menu.</p></div><label htmlFor="master-category-name">Category Name</label><input id="master-category-name" name="name" value={name} onChange={event => { setName(event.target.value); if (formError) setFormError('') }} placeholder="e.g. Wraps, Platters, Beverages" autoComplete="off" autoFocus aria-invalid={Boolean(formError)} aria-describedby={formError ? 'master-category-error' : undefined} />{formError && <p className="admin-form-error" id="master-category-error" role="alert">{formError}</p>}<div className="admin-category-form-actions"><button className="admin-secondary-action" type="button" onClick={closeForm} disabled={submitting}>Cancel</button><button className="admin-primary-action" type="submit" disabled={submitting}>{submitting ? 'Creating...' : 'Create Category'}</button></div></form>}
    {editingCategory && <form className="admin-category-form admin-category-edit-form" onSubmit={updateCategory} noValidate><div><span className="admin-panel-eyebrow">EDIT MASTER CATEGORY</span><h2>Edit Master Category</h2><p>Update the name of this centrally managed category.</p></div><label htmlFor="edit-master-category-name">Category Name</label><input id="edit-master-category-name" name="name" value={editName} onChange={event => { setEditName(event.target.value); if (editError) setEditError('') }} autoComplete="off" autoFocus aria-invalid={Boolean(editError)} aria-describedby={editError ? 'edit-master-category-error' : undefined} />{editError && <p className="admin-form-error" id="edit-master-category-error" role="alert">{editError}</p>}<div className="admin-category-form-actions"><button className="admin-secondary-action" type="button" onClick={closeEdit} disabled={editSubmitting}>Cancel</button><button className="admin-primary-action" type="submit" disabled={editSubmitting}>{editSubmitting ? 'Saving...' : 'Save Changes'}</button></div></form>}
    {statusCategory && <form className="admin-category-form admin-category-status-form" onSubmit={updateStatus} noValidate role="dialog" aria-modal="true" aria-labelledby="category-status-title"><div><span className="admin-panel-eyebrow">{statusCategory.is_active ? 'ARCHIVE CATEGORY' : 'ACTIVATE CATEGORY'}</span><h2 id="category-status-title">{statusCategory.is_active ? 'Archive Category' : 'Activate Category'}</h2><p>{statusCategory.is_active ? `Are you sure you want to archive '${statusCategory.name}'? Archiving keeps the category and its existing menu items, but marks the category inactive.` : `Do you want to activate '${statusCategory.name}' again?`}</p></div>{statusError && <p className="admin-form-error" role="alert">{statusError}</p>}<div className="admin-category-form-actions"><button className="admin-secondary-action" type="button" onClick={closeStatus} disabled={statusSubmitting}>Cancel</button><button className="admin-primary-action" type="submit" disabled={statusSubmitting}>{statusSubmitting ? 'Saving...' : statusCategory.is_active ? 'Archive Category' : 'Activate Category'}</button></div></form>}
    {status === 'loading' && <div className="admin-branch-feedback" role="status">Loading master categories...</div>}
    {status === 'error' && <div className="admin-branch-feedback admin-branch-feedback-error" role="alert"><p>Unable to load master categories.</p><button className="admin-retry-button" type="button" onClick={loadCategories}><RefreshCw /> Retry</button></div>}
    {status === 'ready' && !categories.length && <div className="admin-branch-feedback" role="status">No master categories yet.</div>}
    {status === 'ready' && categories.length > 0 && <div className="admin-category-table-wrap"><table className="admin-category-table"><caption className="sr-only">Master menu categories</caption><thead><tr><th scope="col">Order</th><th scope="col">Category</th><th scope="col">Menu Items</th><th scope="col">Status</th><th scope="col">Actions</th></tr></thead><tbody>{categories.map(category => <tr key={category.id}><td data-label="Order"><span className="admin-category-order">#{category.position ?? '—'}</span></td><td data-label="Category"><strong>{category.name}</strong></td><td data-label="Menu Items">{category.menu_item_count}</td><td data-label="Status"><span className={`admin-category-status ${category.is_active ? 'active' : 'archived'}`}><i />{category.is_active ? 'Active' : 'Archived'}</span></td><td data-label="Actions"><div className="admin-category-actions"><button className="admin-category-edit-action" type="button" onClick={() => openEdit(category)} aria-label={`Edit ${category.name}`}><Pencil /> Edit</button><button className="admin-category-status-action" type="button" onClick={() => openStatus(category)} aria-label={`${category.is_active ? 'Archive' : 'Activate'} ${category.name}`}>{category.is_active ? <Archive /> : <CheckCircle />}{category.is_active ? 'Archive' : 'Activate'}</button></div></td></tr>)}</tbody></table></div>}
  </section>;
}
