import React, { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, BookOpen, RefreshCw, Search, Clock3, Leaf, Star, Plus, Pencil, Archive, CheckCircle, SlidersHorizontal } from 'lucide-react';
import MenuItemCustomizations from './MenuItemCustomizations';

const API = import.meta.env.VITE_API_URL || 'http://localhost:4000/api';
const request = async (path, options = {}) => { const token = sessionStorage.getItem('shawarmaholics_admin_token') || ''; const response = await fetch(`${API}${path}`, { headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: 'Bearer ' + token } : {}), ...options.headers }, ...options }); const data = await response.json().catch(() => ({})); if (!response.ok) { const error = new Error(data.message || 'Request failed'); error.status = response.status; throw error } return data };
const money = new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 2 });

export default function MasterMenu({ onBack }) {
  const [items, setItems] = useState([]), [categoryOptions, setCategoryOptions] = useState([]), [status, setStatus] = useState('loading'), [search, setSearch] = useState(''), [categoryFilter, setCategoryFilter] = useState('all'), [availability, setAvailability] = useState('all'), [showForm, setShowForm] = useState(false), [formError, setFormError] = useState(''), [submitting, setSubmitting] = useState(false), [itemName, setItemName] = useState(''), [description, setDescription] = useState(''), [itemCategory, setItemCategory] = useState(''), [price, setPrice] = useState(''), [imageUrl, setImageUrl] = useState(''), [preparationMinutes, setPreparationMinutes] = useState('10'), [vegetarian, setVegetarian] = useState(false), [bestseller, setBestseller] = useState(false), [available, setAvailable] = useState(true), [editingItem, setEditingItem] = useState(null), [editForm, setEditForm] = useState(null), [editError, setEditError] = useState(''), [editSubmitting, setEditSubmitting] = useState(false), [statusItem, setStatusItem] = useState(null), [statusError, setStatusError] = useState(''), [statusSubmitting, setStatusSubmitting] = useState(false), [customizationItem, setCustomizationItem] = useState(null);
  const loadItems = () => { setStatus('loading'); Promise.all([request('/admin/menu/items'), request('/admin/menu/categories')]).then(([menuData, categoryData]) => { setItems(Array.isArray(menuData.items) ? menuData.items : []); setCategoryOptions(Array.isArray(categoryData.categories) ? categoryData.categories : []); setStatus('ready') }).catch(() => setStatus('error')) };
  useEffect(() => { loadItems() }, []);
  const categoriesUsed = useMemo(() => new Set(items.map(item => item.category_id).filter(id => id != null)).size, [items]);
  const filteredItems = useMemo(() => { const term = search.trim().toLowerCase(); return items.filter(item => (!term || String(item.name || '').toLowerCase().includes(term)) && (categoryFilter === 'all' || String(item.category_id) === categoryFilter) && (availability === 'all' || (availability === 'available' ? item.available === true : item.available !== true))) }, [items, search, categoryFilter, availability]);
  const availableCount = items.filter(item => item.available === true).length;
  const activeCategories = categoryOptions.filter(category => category.is_active === true);
  const openForm = () => { setShowForm(true); setFormError(''); setItemCategory(activeCategories[0] ? String(activeCategories[0].id) : '') };
  const closeForm = () => { setShowForm(false); setFormError(''); setItemName(''); setDescription(''); setItemCategory(''); setPrice(''); setImageUrl(''); setPreparationMinutes('10'); setVegetarian(false); setBestseller(false); setAvailable(true) };
  const createItem = async event => { event.preventDefault(); const trimmedName = itemName.trim(); const numericPrice = Number(price); const prep = Number(preparationMinutes); if (!trimmedName) { setFormError('Please enter an item name.'); return } if (!itemCategory) { setFormError('Please select an active category.'); return } if (price.trim() === '' || !Number.isFinite(numericPrice) || numericPrice < 0) { setFormError('Enter a valid non-negative master price.'); return } if (!Number.isInteger(prep) || prep < 0) { setFormError('Preparation time must be a non-negative integer.'); return } setSubmitting(true); setFormError(''); try { await request('/admin/menu/items', { method: 'POST', body: JSON.stringify({ name: trimmedName, description: description.trim() || null, category_id: Number(itemCategory), price: numericPrice, image_url: imageUrl.trim() || null, available, bestseller, vegetarian, preparation_minutes: prep }) }); closeForm(); await loadItems() } catch (error) { setFormError(error.status === 400 || error.status === 404 ? error.message : 'Unable to create menu item. Please try again.') } finally { setSubmitting(false) } };
  const openEdit = item => { setShowForm(false); setFormError(''); setEditingItem(item); setEditForm({ name: item.name || '', description: item.description || '', category_id: String(item.category_id ?? ''), price: item.price == null ? '' : String(item.price), image_url: item.image_url || '', preparation_minutes: String(item.preparation_minutes ?? 10), vegetarian: item.vegetarian === true, bestseller: item.bestseller === true, available: item.available === true }); setEditError('') };
  const closeEdit = () => { setEditingItem(null); setEditForm(null); setEditError('') };
  const openStatus = item => { setShowForm(false); setEditingItem(null); setStatusItem(item); setStatusError('') };
  const closeStatus = () => { setStatusItem(null); setStatusError('') };
  const setEditField = (field, value) => setEditForm(current => ({ ...current, [field]: value }));
  const updateItem = async event => { event.preventDefault(); const form = editForm || {}; const trimmedName = String(form.name || '').trim(); const numericPrice = Number(form.price); const prep = Number(form.preparation_minutes); if (!trimmedName) { setEditError('Please enter an item name.'); return } if (!form.category_id) { setEditError('Please select a category.'); return } if (String(form.price).trim() === '' || !Number.isFinite(numericPrice) || numericPrice < 0) { setEditError('Enter a valid non-negative master price.'); return } if (!Number.isInteger(prep) || prep < 0) { setEditError('Preparation time must be a non-negative integer.'); return } setEditSubmitting(true); setEditError(''); try { await request(`/admin/menu/items/${editingItem.id}`, { method: 'PATCH', body: JSON.stringify({ name: trimmedName, description: String(form.description || '').trim() || null, category_id: Number(form.category_id), price: numericPrice, image_url: String(form.image_url || '').trim() || null, available: form.available === true, bestseller: form.bestseller === true, vegetarian: form.vegetarian === true, preparation_minutes: prep }) }); closeEdit(); await loadItems() } catch (error) { setEditError(error.status === 400 || error.status === 404 ? error.message : 'Unable to update menu item. Please try again.') } finally { setEditSubmitting(false) } };
  const updateStatus = async event => { event.preventDefault(); const nextStatus = !(statusItem.is_active !== false); setStatusSubmitting(true); setStatusError(''); try { await request(`/admin/menu/items/${statusItem.id}/status`, { method: 'PATCH', body: JSON.stringify({ is_active: nextStatus }) }); closeStatus(); await loadItems() } catch (error) { setStatusError(error.status === 400 || error.status === 404 ? error.message : 'Unable to update menu item status. Please try again.') } finally { setStatusSubmitting(false) } };
  if (customizationItem) return <MenuItemCustomizations item={customizationItem} onBack={() => setCustomizationItem(null)} />;
  return <section className="admin-master-menu" aria-labelledby="master-menu-title">
    <button className="admin-back-button" type="button" onClick={onBack}><ArrowLeft /> Back to Head Office</button>
    <header className="admin-master-menu-header"><div className="admin-state-icon"><BookOpen /></div><div className="admin-master-menu-title"><span className="admin-panel-eyebrow">HEAD OFFICE / MASTER MENU</span><h1 id="master-menu-title">Master Menu</h1><p>Manage the global menu owned by Head Office.</p></div><button className="admin-primary-action" type="button" onClick={openForm}><Plus /> Add Menu Item</button></header>
    {showForm && <form className="admin-menu-create-form" onSubmit={createItem} noValidate><div><span className="admin-panel-eyebrow">NEW MASTER MENU ITEM</span><h2>Add Menu Item</h2><p>Create a centrally managed item for the Shawarmaholics master menu.</p></div><div className="admin-menu-form-grid"><label>Item Name *<input value={itemName} onChange={event => setItemName(event.target.value)} placeholder="e.g. Classic Chicken Shawarma" autoFocus autoComplete="off" /></label><label>Master Price *<input value={price} onChange={event => setPrice(event.target.value)} placeholder="199" type="number" min="0" step="0.01" /></label><label className="admin-menu-form-wide">Description<textarea value={description} onChange={event => setDescription(event.target.value)} placeholder="Describe the item" rows="3" /></label><label>Category *<select value={itemCategory} onChange={event => setItemCategory(event.target.value)} disabled={!activeCategories.length}><option value="">{activeCategories.length ? 'Select active category' : 'No active categories available'}</option>{activeCategories.map(category => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label>Preparation Time (minutes)<input value={preparationMinutes} onChange={event => setPreparationMinutes(event.target.value)} type="number" min="0" step="1" /></label><label className="admin-menu-form-wide">Image URL (optional)<input value={imageUrl} onChange={event => setImageUrl(event.target.value)} placeholder="https://..." type="url" /></label></div><div className="admin-menu-checkboxes"><label><input checked={vegetarian} onChange={event => setVegetarian(event.target.checked)} type="checkbox" /> Vegetarian</label><label><input checked={bestseller} onChange={event => setBestseller(event.target.checked)} type="checkbox" /> Bestseller</label><label><input checked={available} onChange={event => setAvailable(event.target.checked)} type="checkbox" /> Available</label></div>{formError && <p className="admin-form-error" role="alert">{formError}</p>}<div className="admin-category-form-actions"><button className="admin-secondary-action" type="button" onClick={closeForm} disabled={submitting}>Cancel</button><button className="admin-primary-action" type="submit" disabled={submitting || !activeCategories.length}>{submitting ? 'Creating...' : 'Create Menu Item'}</button></div></form>}
    {editingItem && editForm && <form className="admin-menu-create-form admin-menu-edit-form" onSubmit={updateItem} noValidate role="dialog" aria-modal="true" aria-labelledby="edit-menu-item-title"><div><span className="admin-panel-eyebrow">EDIT MASTER MENU ITEM</span><h2 id="edit-menu-item-title">Edit Menu Item</h2><p>Update the centrally managed master menu item.</p></div><div className="admin-menu-form-grid"><label>Item Name *<input value={editForm.name} onChange={event => setEditField('name', event.target.value)} autoFocus autoComplete="off" /></label><label>Master Price *<input value={editForm.price} onChange={event => setEditField('price', event.target.value)} type="number" min="0" step="0.01" /></label><label className="admin-menu-form-wide">Description<textarea value={editForm.description} onChange={event => setEditField('description', event.target.value)} rows="3" /></label><label>Category *<select value={editForm.category_id} onChange={event => setEditField('category_id', event.target.value)}>{categoryOptions.filter(category => category.is_active === true || String(category.id) === String(editingItem.category_id)).map(category => <option key={category.id} value={category.id}>{category.name}{category.is_active === false ? ' (Archived — select an active category)' : ''}</option>)}</select>{editingItem.category_is_active === false && <small className="admin-menu-form-warning">This item is currently in an archived category. Keep it unchanged or select an active category.</small>}</label><label>Preparation Time (minutes)<input value={editForm.preparation_minutes} onChange={event => setEditField('preparation_minutes', event.target.value)} type="number" min="0" step="1" /></label><label className="admin-menu-form-wide">Image URL (optional)<input value={editForm.image_url} onChange={event => setEditField('image_url', event.target.value)} type="url" /></label></div><div className="admin-menu-checkboxes"><label><input checked={editForm.vegetarian} onChange={event => setEditField('vegetarian', event.target.checked)} type="checkbox" /> Vegetarian</label><label><input checked={editForm.bestseller} onChange={event => setEditField('bestseller', event.target.checked)} type="checkbox" /> Bestseller</label><label><input checked={editForm.available} onChange={event => setEditField('available', event.target.checked)} type="checkbox" /> Available</label></div>{editError && <p className="admin-form-error" role="alert">{editError}</p>}<div className="admin-category-form-actions"><button className="admin-secondary-action" type="button" onClick={closeEdit} disabled={editSubmitting}>Cancel</button><button className="admin-primary-action" type="submit" disabled={editSubmitting}>{editSubmitting ? 'Saving...' : 'Save Changes'}</button></div></form>}
    {statusItem && <form className="admin-menu-create-form admin-menu-status-form" onSubmit={updateStatus} noValidate role="dialog" aria-modal="true" aria-labelledby="menu-item-status-title"><div><span className="admin-panel-eyebrow">{statusItem.is_active !== false ? 'ARCHIVE MASTER ITEM' : 'ACTIVATE MASTER ITEM'}</span><h2 id="menu-item-status-title">{statusItem.is_active !== false ? 'Archive Item' : 'Activate Item'}</h2><p>{statusItem.is_active !== false ? `Are you sure you want to archive '${statusItem.name}'? Archiving keeps the master menu item and its historical relationships but marks it inactive.` : `Do you want to activate '${statusItem.name}' again?`}</p></div>{statusError && <p className="admin-form-error" role="alert">{statusError}</p>}<div className="admin-category-form-actions"><button className="admin-secondary-action" type="button" onClick={closeStatus} disabled={statusSubmitting}>Cancel</button><button className="admin-primary-action" type="submit" disabled={statusSubmitting}>{statusSubmitting ? 'Saving...' : statusItem.is_active !== false ? 'Archive Item' : 'Activate Item'}</button></div></form>}
    <div className="admin-master-menu-summary" aria-label="Master menu summary"><div><span>Total Items</span><strong>{items.length}</strong></div><div><span>Available Items</span><strong>{availableCount}</strong></div><div><span>Unavailable Items</span><strong>{items.length - availableCount}</strong></div><div><span>Categories Used</span><strong>{categoriesUsed}</strong></div></div>
    {status === 'ready' && items.length > 0 && <div className="admin-master-menu-filters"><label className="admin-menu-search"><Search /><span className="sr-only">Search menu items</span><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search by item name" type="search" /></label><label><span>Category</span><select value={categoryFilter} onChange={event => setCategoryFilter(event.target.value)}><option value="all">All categories</option>{categoryOptions.map(category => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label><span>Availability</span><select value={availability} onChange={event => setAvailability(event.target.value)}><option value="all">All</option><option value="available">Available</option><option value="unavailable">Unavailable</option></select></label></div>}
    {status === 'loading' && <div className="admin-branch-feedback" role="status">Loading master menu...</div>}
    {status === 'error' && <div className="admin-branch-feedback admin-branch-feedback-error" role="alert"><p>Unable to load master menu.</p><button className="admin-retry-button" type="button" onClick={loadItems}><RefreshCw /> Retry</button></div>}
    {status === 'ready' && !items.length && <div className="admin-branch-feedback" role="status">No master menu items yet.</div>}
    {status === 'ready' && items.length > 0 && !filteredItems.length && <div className="admin-branch-feedback" role="status">No menu items match the selected filters.</div>}
    {status === 'ready' && filteredItems.length > 0 && <div className="admin-master-menu-table-wrap"><table className="admin-master-menu-table"><caption className="sr-only">Head Office master menu items</caption><thead><tr><th scope="col">Item</th><th scope="col">Category</th><th scope="col">Master Price</th><th scope="col">Lifecycle</th><th scope="col">Availability</th><th scope="col">Details</th><th scope="col">Actions</th></tr></thead><tbody>{filteredItems.map(item => <tr key={item.id}><td data-label="Item"><strong>{item.name || 'Unnamed item'}</strong>{item.description && <small>{item.description}</small>}</td><td data-label="Category"><span className="admin-menu-category-name">{item.category_name || 'Uncategorized'}</span>{item.category_is_active === false && <span className="admin-menu-archived-label">Archived category</span>}</td><td data-label="Master Price" className="admin-menu-price">{item.price == null ? '—' : money.format(Number(item.price))}</td><td data-label="Lifecycle"><span className={`admin-menu-lifecycle ${item.is_active !== false ? 'active' : 'archived'}`}>{item.is_active !== false ? 'Active' : 'Archived'}</span></td><td data-label="Availability"><span className={`admin-menu-availability ${item.available === true ? 'available' : 'unavailable'}`}>{item.available === true ? 'Available' : 'Unavailable'}</span></td><td data-label="Details"><div className="admin-menu-badges">{item.bestseller === true && <span className="admin-menu-badge"><Star /> Bestseller</span>}{item.vegetarian === true && <span className="admin-menu-badge"><Leaf /> Vegetarian</span>}{item.preparation_minutes != null && <span className="admin-menu-badge"><Clock3 /> {item.preparation_minutes} min</span>}</div></td><td data-label="Actions"><div className="admin-category-actions"><button className="admin-category-edit-action" type="button" onClick={() => setCustomizationItem(item)} aria-label={`Manage customizations for ${item.name}`}><SlidersHorizontal /> Customizations</button><button className="admin-category-edit-action" type="button" onClick={() => openEdit(item)} aria-label={`Edit ${item.name}`}><Pencil /> Edit</button><button className="admin-category-status-action" type="button" onClick={() => openStatus(item)} aria-label={`${item.is_active !== false ? 'Archive' : 'Activate'} ${item.name}`}>{item.is_active !== false ? <Archive /> : <CheckCircle />}{item.is_active !== false ? 'Archive' : 'Activate'}</button></div></td></tr>)}</tbody></table></div>}
  </section>;
}
