import React,{useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {Bell,Check,ChefHat,Clock3,Flame,Package,Volume2,VolumeX} from 'lucide-react';
import {io} from 'socket.io-client';
import {recalculateKitchenQueue} from './kitchenQueue';
import KitchenPerformance from './KitchenPerformance';
import KitchenAlerts from './KitchenAlerts.jsx';
import {alertKey,elapsedSeconds,formatDuration,loadAlertLedger,rememberAlert,targetSeconds} from './kitchenAlerts';
import './kds.css';

const API=import.meta.env.VITE_API_URL||'http://localhost:4000/api';
const api=(path,opts={})=>fetch(API+path,{headers:{'Content-Type':'application/json',...opts.headers},...opts}).then(async r=>{const data=await r.json().catch(()=>({}));if(!r.ok){const error=Error(data.message||'Request failed');error.status=r.status;error.payload=data;throw error}return data});
const money=n=>`₹${Number(n||0).toLocaleString('en-IN')}`;
const Pill=({children,tone=''})=><span className={'pill '+tone}>{children}</span>;
function OrderDetails({order}){const items=Array.isArray(order.items)?order.items:[];const instructions=[order.special_request,order.specialRequest,...items.flatMap(item=>{const c=item.customizations||{};return [item.special_request,item.specialRequest,c.special_request,c.specialRequest]} )].filter(value=>typeof value==='string'&&value.trim());return <div className="kds-order-details">{items.map(item=>{const c=item.customizations||{};const extras=Array.isArray(c.extras)?c.extras.filter(extra=>extra?.name):[];const sauce=c.sauce?.name||c.sauce_name||item.sauce?.name;return <div className="kds-item" key={item.id||item.name}><p className="kds-item-name"><b>{item.quantity||0}×</b> <strong>{item.name||'Unnamed item'}</strong></p>{sauce&&<small><b>Sauce:</b> {sauce}</small>}{extras.length>0&&<small><b>Extras:</b> {extras.map(x=>`${x.name}${x.quantity>1?` ×${x.quantity}`:''}`).join(', ')}</small>}{c.customizations&&<small><b>Customizations:</b> {c.customizations}</small>}</div>})}{instructions.length>0&&<div className="kds-instructions"><b>⚠ SPECIAL INSTRUCTIONS</b>{[...new Set(instructions)].map((instruction,index)=><span key={`${instruction}-${index}`}>⚠ {instruction}</span>)}</div>}</div>}
function Timer({order}){const [now,setNow]=useState(Date.now());useEffect(()=>{const id=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(id)},[]);const started=order.activated_at||order.preparation_started_at;const target=Number(order.target_prep_seconds)||480;const seconds=started?Math.max(0,Math.floor((now-new Date(started).getTime())/1000)):0;const minutes=String(Math.floor(seconds/60)).padStart(2,'0'),rest=String(seconds%60).padStart(2,'0'),delayed=seconds>target,attention=!delayed&&seconds>target*.75,status=delayed?'delayed':attention?'attention':'on-track',label=delayed?'DELAYED':attention?'ATTENTION':'ON TRACK';return <div className={`kds-timer ${status}`} aria-label={`${label}, ${minutes}:${rest}`}><b>{delayed?'⚠ ':''}{minutes}:{rest}</b><span className="kds-timer-status">{delayed?'⚠ ':attention?'◐ ':'✓ '}{label}</span><small>Target: {formatDuration(target)}</small></div>}

function KitchenDisplay({onMode}){
  const [orders,setOrders]=useState([]),[stock,setStock]=useState([]),[toast,setToast]=useState(null),[alerts,setAlerts]=useState([]),[completing,setCompleting]=useState(()=>new Set()),[sound,setSound]=useState(()=>localStorage.getItem('kds-sound')!=='off'),[online,setOnline]=useState(false),[clock,setClock]=useState(new Date()),[stockFilter,setStockFilter]=useState('all'),[editingStock,setEditingStock]=useState(null),[view,setView]=useState('orders');
  const queue=useMemo(()=>recalculateKitchenQueue(orders),[orders]);
  const alertLedger=useRef(loadAlertLedger()),ordersReady=useRef(false),stockReady=useRef(false),soundRef=useRef(sound),completingRef=useRef(new Set());
  useEffect(()=>{soundRef.current=sound},[sound]);
  const dismissAlert=useCallback(id=>setAlerts(current=>current.filter(alert=>alert.id!==id)),[]);
  const notify=useCallback(alert=>{setAlerts(current=>[...current,alert]);if(soundRef.current&&typeof window!=='undefined'&&window.AudioContext){try{const context=new AudioContext(),oscillator=context.createOscillator(),gain=context.createGain();oscillator.frequency.value=alert.type==='outOfStock'?520:alert.type==='delayed'?440:660;gain.gain.setValueAtTime(.035,context.currentTime);gain.gain.exponentialRampToValueAtTime(.001,context.currentTime+.18);oscillator.connect(gain).connect(context.destination);oscillator.start();oscillator.stop(context.currentTime+.18);oscillator.addEventListener('ended',()=>context.close())}catch{}}},[]);
  const notifyOnce=useCallback((type,id,alert)=>{const key=alertKey(type,id);return rememberAlert(alertLedger.current,key)?(notify({...alert,id:key,type}),true):false},[notify]);
  useEffect(()=>{const tick=setInterval(()=>setClock(new Date()),1000);return()=>clearInterval(tick)},[]);
  useEffect(()=>{
    api('/kitchen/orders').then(x=>{const initial=x.orders||[];initial.forEach(order=>{if(elapsedSeconds(order)>=targetSeconds(order))rememberAlert(alertLedger.current,alertKey('delayed',order.id))});setOrders(initial);ordersReady.current=true}).catch(()=>{setOrders([]);ordersReady.current=true});
    api('/inventory').then(x=>{setStock(x.items||[]);stockReady.current=true}).catch(()=>{setStock([]);stockReady.current=true});
    const socket=io(API.replace('/api',''));const add=order=>setOrders(current=>current.some(x=>x.id===order.id)?current:[...current,order]);
    socket.on('connect',()=>setOnline(true));socket.on('disconnect',()=>setOnline(false));
    socket.on('order:new',order=>{add(order);const count=(order.items||[]).reduce((sum,item)=>sum+Number(item.quantity||0),0);notifyOnce('newOrder',order.id,{title:`Order #${order.order_number}`,message:`${count} item${count===1?'':'s'} added to the kitchen queue`})});
    socket.on('order:updated',updated=>setOrders(current=>current.map(x=>x.id===updated.id?{...x,...updated}:x).filter(x=>!['completed','cancelled'].includes(x.status))));
    socket.on('inventory.updated',updated=>setStock(current=>{const previous=current.find(item=>item.id===updated.id);if(stockReady.current&&previous&&previous.status!==updated.status&&(updated.status==='low'||updated.status==='out'))notifyOnce(updated.status==='out'?'outOfStock':'lowStock',updated.id,{title:updated.name,message:updated.status==='out'?'Ingredient unavailable.':`${updated.quantity} ${updated.unit} remaining`});return current.map(x=>x.id===updated.id?{...x,...updated}:x)}));
    return()=>socket.disconnect();
  },[notifyOnce]);
  useEffect(()=>{if(view!=='orders')return;queue.active.filter(order=>order.status!=='preparing').forEach(order=>{api(`/kitchen/orders/${order.id}/status`,{method:'PATCH',body:JSON.stringify({status:'preparing'})}).then(({order:updated})=>setOrders(current=>current.map(x=>x.id===updated.id?{...x,...updated}:x))).catch(()=>{})})},[queue.active,view]);
  useEffect(()=>{if(!ordersReady.current||view!=='orders')return;queue.active.forEach(order=>{const elapsed=elapsedSeconds(order,clock.getTime()),target=targetSeconds(order);if(elapsed>target)notifyOnce('delayed',order.id,{title:`Order #${order.order_number}`,message:`Preparation time exceeded target. Target: ${formatDuration(target)} · Current: ${formatDuration(elapsed)}`})})},[queue.active,clock,notifyOnce,view]);
  const complete=async order=>{if(completingRef.current.has(order.id))return;completingRef.current.add(order.id);setCompleting(current=>new Set(current).add(order.id));try{const {order:updated}=await api(`/kitchen/orders/${order.id}/status`,{method:'PATCH',body:JSON.stringify({status:'completed'})});setOrders(current=>current.map(x=>x.id===updated.id?updated:x));setToast(`ORDER #${order.order_number} completed`);setTimeout(()=>setToast(null),3500)}catch(error){if(error.status===409){try{const latest=await api('/kitchen/orders');setOrders(latest.orders||[]);setToast(`ORDER #${order.order_number} was already completed elsewhere`)}catch{setToast('This order was completed, but the queue could not be refreshed')}}else setToast('Unable to complete order. Please try again.')}finally{completingRef.current.delete(order.id);setCompleting(current=>{const next=new Set(current);next.delete(order.id);return next})}};
  const toggleSound=()=>setSound(value=>{localStorage.setItem('kds-sound',value?'off':'on');return !value});
  const saveStock=async()=>{if(!editingStock)return;const status=editingStock.nextStatus,quantity=status==='out'?0:status==='low'?Math.min(Number(editingStock.quantity),Number(editingStock.threshold||1)):Math.max(Number(editingStock.quantity),Number(editingStock.threshold||1)+1);try{const {item}=await api(`/inventory/${editingStock.id}`,{method:'PATCH',body:JSON.stringify({quantity})});setStock(current=>current.map(x=>x.id===item.id?{...x,...item}:x));setEditingStock(null)}catch{setToast('Unable to update stock')}};
  const low=stock.filter(x=>x.status==='low'),out=stock.filter(x=>x.status==='out'),visibleStock=stock.filter(x=>stockFilter==='all'||x.status===stockFilter);const attention={delayed:queue.active.filter(order=>elapsedSeconds(order,clock.getTime())>targetSeconds(order)).length,out:out.length};const nav=[['Orders',ChefHat,'orders'],['Stock Status',Package,'orders'],['Performance',Flame,'performance']];
  const orderView=<><header className="kds-header"><div><Pill>LIVE WORKFLOW</Pill><h1>Kitchen <em>display</em></h1><p>Real-time Orders · Smart Queue · Efficient Workflow</p></div><div className="kitchen-online"><span className={online?'online-dot':'offline-dot'}/>{online?'Kitchen Online':'Kitchen Offline'}<br/><small>{clock.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})} · {clock.toLocaleDateString()}</small></div></header><div className="kds-content"><div className="section-heading"><h2>🔥 ACTIVE ORDERS <span>({queue.active.length}/2)</span></h2><small>MAX 2 · AUTOMATIC FCFS</small></div><div className="active-orders">{queue.active.length?queue.active.map(order=><article className="kds-order-card" key={order.id}><div><Pill>{order.order_type==='EAT HERE'?'DINE IN':'TAKEAWAY'}</Pill><h2>#{order.order_number}</h2><small><Clock3/> Received {new Date(order.created_at).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</small></div><Timer order={order}/><OrderDetails order={order}/><button className="primary complete-button" onClick={()=>complete(order)} disabled={completing.has(order.id)} aria-busy={completing.has(order.id)}><Check/> {completing.has(order.id)?'COMPLETING...':'ORDER COMPLETED'}</button></article>):<div className="empty"><ChefHat/><h2>Ready for the next order</h2><p>New orders will move here automatically.</p></div>}</div><div className="section-heading"><h2>UP NEXT</h2><small>AUTOMATICALLY ACTIVATED</small></div>{queue.upNext?<article className="kds-up-next-card"><div><Pill>{queue.upNext.order_type==='EAT HERE'?'DINE IN':'TAKEAWAY'}</Pill><h3>#{queue.upNext.order_number}</h3><OrderDetails order={queue.upNext}/></div><span>Will automatically move to Active<br/>when an active order is completed.</span></article>:<p className="muted">No order waiting to move up next.</p>}<div className="section-heading"><h2>WAITING QUEUE <span>({queue.waiting.length})</span></h2><small>FIRST COME · FIRST SERVE</small></div><div className="kds-queue">{queue.waiting.slice(0,5).map(order=><article className="kds-queue-card" key={order.id}><b>#{order.order_number}</b><span>{order.items?.map(i=>`${i.name} ×${i.quantity}`).join(' · ')}</span><small>{new Date(order.created_at).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</small></article>)}{queue.waiting.length>5&&<p className="muted">+ {queue.waiting.length-5} more orders</p>}</div></div><footer className="kds-footer"><button onClick={toggleSound}>{sound?<Volume2/>:<VolumeX/>} Sound Alerts {sound?'ON':'OFF'}</button><span>Complete orders on time to keep the flow smooth.</span></footer></>;
  return <main className="kds-app"><aside className="kds-sidebar"><div className="brand light"><span>SHAWARMA</span><b>HOLICS</b><small>WRAPS. LOADED. OBSESSED.</small></div><Pill> BELGAUM </Pill>{nav.map(([label,Icon,target])=><button key={label} onClick={()=>setView(target)} className={view===target&&label==='Orders'?'active':''}><Icon/>{label}</button>)}<div className="staff-summary"><small>TODAY'S SUMMARY</small><span><b>{orders.length}</b> Orders in queue</span><span><b>{queue.active.length}</b> Active</span><span><b>{queue.waiting.length}</b> Waiting</span><span><b>{out.length}</b> Out of stock</span></div><button className="mode lightmode" onClick={onMode}>Open kiosk</button></aside><section className="kds-main-layout"><div className="kds-view-content">{view==='performance'?<KitchenPerformance/>:orderView}</div></section><aside className="kds-stock-column"><Pill>LIVE INVENTORY</Pill><h2>Stock status</h2><div className="stock-filter"><button className={stockFilter==='all'?'selected':''} onClick={()=>setStockFilter('all')}>All</button><button className={stockFilter==='low'?'selected':''} onClick={()=>setStockFilter('low')}>Low ({low.length})</button><button className={stockFilter==='out'?'selected':''} onClick={()=>setStockFilter('out')}>Out ({out.length})</button></div><div className="kds-stock-list">{visibleStock.map(item=><article className="kds-stock-item" key={item.id}><span className={'stock-dot '+item.status}/><div><b>{item.name}</b><small>Qty: {item.quantity} {item.unit}</small></div><button className="stock-edit" onClick={()=>setEditingStock({...item,nextStatus:item.status})}><Pill tone={item.status}>{item.status==='out'?'OUT OF STOCK':item.status==='low'?'LOW STOCK':'AVAILABLE'}</Pill></button></article>)}{!visibleStock.length&&<p className="muted">Everything is fully stocked.</p>}</div><button className="secondary" onClick={()=>stock[0]&&setEditingStock({...stock[0],nextStatus:stock[0].status})}>UPDATE STOCK STATUS</button></aside><KitchenAlerts alerts={alerts} onDismiss={dismissAlert} attention={attention}/>{toast&&<div className="kds-toast"><Bell/> {toast}</div>}{editingStock&&<div className="stock-modal-backdrop"><div className="stock-modal"><h2>Update stock status</h2><p>{editingStock.name} · Qty {editingStock.quantity} {editingStock.unit}</p>{['available','low','out'].map(status=><button key={status} className={editingStock.nextStatus===status?'selected':''} onClick={()=>setEditingStock({...editingStock,nextStatus:status})}>{status==='out'?'OUT OF STOCK':status==='low'?'LOW STOCK':'AVAILABLE'}</button>)}<div><button className="secondary" onClick={()=>setEditingStock(null)}>Cancel</button><button className="primary" onClick={saveStock}>Save</button></div></div></div>}</main>;
}

export default KitchenDisplay;
