import React,{useEffect,useMemo,useState} from 'react';
import {ArrowLeft,ArrowRight,CheckCircle2,ShieldCheck} from 'lucide-react';
import {requestOtp,verifyOtp} from '../services/attendanceService';

const friendlyError=error=>{if(error.status===404)return 'That phone number is not registered for staff attendance.';if(error.status===403)return 'This staff profile is inactive. Please contact a manager.';if(error.status===401)return error.message||'The verification code is incorrect or expired.';if(error.status===409)return 'Attendance state changed. Request a new verification code.';if(error.status===429)return 'Please wait a moment before requesting another code.';return error.network?'Unable to connect to the attendance service.':'Unable to complete attendance verification. Please try again.'};

function AttendanceSuccess({result,onBack}){const punchOut=result.action==='punch_out';return <section className={`attendance-result ${punchOut?'punch-out':'punch-in'}`}><div className="attendance-success-icon"><CheckCircle2/></div><span className="attendance-eyebrow">{punchOut?'PUNCH OUT SUCCESSFUL':'PUNCH IN SUCCESSFUL'}</span><h1>{punchOut?'Your attendance has been recorded successfully.':'Your attendance has been marked successfully.'}</h1><button className="primary attendance-action" onClick={onBack}>BACK TO KITCHEN <ArrowRight/></button></section>}

export default function StaffAttendance({onBack}){
  const [step,setStep]=useState('phone'),[phone,setPhone]=useState(''),[otp,setOtp]=useState(''),[loading,setLoading]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[result,setResult]=useState(null),[requestedAction,setRequestedAction]=useState('punch_in'),[cooldown,setCooldown]=useState(0);
  useEffect(()=>{if(!cooldown)return;const id=setInterval(()=>setCooldown(value=>Math.max(0,value-1)),1000);return()=>clearInterval(id)},[cooldown]);
  const validPhone=/^\d{10}$/.test(phone.replace(/\D/g,''));
  const cleanPhone=useMemo(()=>phone.replace(/\D/g,''),[phone]);
  const sendOtp=async(event)=>{event?.preventDefault();if(!validPhone){setError('Enter your registered 10-digit phone number.');return}setLoading(true);setError('');setNotice('');try{const response=await requestOtp(cleanPhone);setRequestedAction(response.action||'punch_in');setOtp('');setStep('otp');setCooldown(30);setNotice('OTP requested. Check the backend terminal in development mode.')}catch(error){setError(friendlyError(error))}finally{setLoading(false)}};
  const verify=async(event)=>{event?.preventDefault();if(!/^\d{6}$/.test(otp)){setError('Enter the 6-digit verification code.');return}setLoading(true);setError('');try{const response=await verifyOtp(cleanPhone,otp);if(!response?.success||!response.action||!response.staff||!response.attendance)throw Object.assign(new Error('Invalid attendance response'),{status:502});setResult(response);setStep('success')}catch(error){setOtp('');setError(friendlyError(error))}finally{setLoading(false)}};
  if(step==='success'&&result)return <div className="kds-attendance"><AttendanceSuccess result={result} onBack={onBack}/></div>;
  return <div className="kds-attendance"><header className="attendance-header"><div><span className="attendance-eyebrow">STAFF OPERATIONS</span><h1>{step==='phone'?'Staff attendance':'Verify OTP'}</h1><p>{step==='phone'?'Mark your attendance securely':requestedAction==='punch_out'?'Verify to punch out for today':'Verify to punch in for today'}</p></div><ShieldCheck/></header><div className="attendance-card">{step==='phone'?<form onSubmit={sendOtp}><label htmlFor="attendance-phone">Enter your registered phone number</label><div className="phone-field"><span>+91</span><input id="attendance-phone" value={phone} onChange={event=>{setPhone(event.target.value.replace(/\D/g,'').slice(0,10));setError('')}} inputMode="numeric" autoComplete="tel" placeholder="9876543210" aria-describedby="phone-help" autoFocus/></div><small id="phone-help">Use your registered staff mobile number.</small><button className="primary attendance-action" disabled={loading} type="submit">{loading?'SENDING OTP...':'SEND OTP'} <ArrowRight/></button></form>:<form onSubmit={verify}><label htmlFor="attendance-otp">Enter the 6-digit verification code</label><input id="attendance-otp" className="otp-field" value={otp} onChange={event=>{setOtp(event.target.value.replace(/\D/g,'').slice(0,6));setError('')}} inputMode="numeric" autoComplete="one-time-code" maxLength={6} placeholder="••••••" autoFocus aria-describedby="otp-help"/><small id="otp-help">Didn't receive the code? <button className="attendance-link" type="button" disabled={loading||cooldown>0} onClick={sendOtp}>{cooldown?`RESEND OTP (${cooldown}s)`:'RESEND OTP'}</button></small><button className="primary attendance-action" disabled={loading} type="submit">{loading?'VERIFYING...':'VERIFY OTP'} <ArrowRight/></button><button className="attendance-back" type="button" onClick={()=>{setStep('phone');setOtp('');setError('');setNotice('')}}> <ArrowLeft/> Change phone number</button></form>}{notice&&<p className="attendance-notice"><ShieldCheck/> Development mode: OTP is available in the backend server terminal.</p>}{error&&<p className="attendance-error" role="alert">{error}</p>}</div></div>;
}
